### ISSUE TITLE
precision position recepteur

### ISSUE THREAD

**Issue by jxl77** [fanfanlatulipe26/BaliseDGAC_GPS_Logger#10]
Bonjour, 

Je viens d'installer une balise et une autre en mode récepteur. 
Tout marche bien, mais pourquoi ne pas  mettre toutes les décimales dans la position captée par le récepteur ? 
où modifier pour changer cela ? 

Merci

**Comment by fanfanlatulipe26** [comment]
Si "identificateur" signifie nom du réseau Wifi pour le point d"accès on peut envisager de rajouter une option.
Par défaut le point d’accès serait du genre  BALISE_adresse-Mac , mais par un #define on pourrait lui donner un nom quelconque.

Par contre l'identificateur contenu dans le message envoyé par la balise doit rester lié à l'adresse MAC et être unique.

Pour retrouver un modèle après un crash et si on ne suivait pas déjà le modèle sur son portable/PC,  il faut pouvoir continuer à capter la balise, se connecter au point d'accès et récupérer les données GPS.  Cela suppose que le crash n'a pas été mortel et que la porté au sol du Wifi est suffisante (ce qui est loin d'être le cas)
Il est peut être plus intéressant si l'équipement RC le permet d'avoir une télémesure qui renvoie le GPS. On est alors sûr de récupérer les dernières coordonnées valides reçues. D’où le projet d'émuler un capteur GPS de télémesure avec la balise. Cela a été fait je crois pour Frsky et j'ai fait quelques essais avec Flysky/ibus.
L'autre solution est l'option GSM de la balise.
Voir la fin de la discussion de issue #6

**Comment by jxl77** [comment]
Je ne crois pas qu'il y ait d'obligation à ce que l'identifiant soit lié à l'adresse mac. La seule contrainte est d'etre unique. 
Si je fait commencer l'identificateur  par mon indicatif de telepilote, puis un identifiant unique à mon send, le tout sera unique. 

Pour la  recherche après crash, j'ai la pratique de recherche de ballons sondes, avec un émetteur  401Mhz qui envoie les coordonnées GPS.  Bien sur le fin du fin est davoir un retour des coordonnées sur une carte openstret map. 
Mais au besoin, on peut reporter  les coordonnées à la main. 
Pour la portée, il faut bien sur avoir une idée approximative de l'endroit, et une bonne antenne sur son recepteur.

**Comment by fanfanlatulipe26** [comment]
Je viens de créer sur GitHub une nouvelle branche [travail-4.2](https://github.com/fanfanlatulipe26/BaliseDGAC_GPS_Logger/tree/travail-4.2) qui contient la possibilité de modifier l'identifiant de la balise et une option pour rajouter de la télémétrie FLysky/IBus.
24 caractères sont disponibles Les 6 premiers sont figés.
Le n° UAS faisant 16 caractères, il reste 8 caractères pour infos supplémentaires.

Le soft permettait déjà de changer le nom du réseau Wfi pour le point d'accès.

Reste peut être un problème si on utilise le N° UAS dans l'identificateur: je ne sais pas si 2 N° UAS peuvent différer uniquement par des caractères en majuscule/minuscule.
Pour l'identificateur de la balise, l'arrêté du 27 décembre 2019 précise bien que la "casse" n'est pas prise en compte:
`Cet identifiant unique ne doit comporter aucun signe espace. En outre, l'unicité de cet identifiant ne pourra être obtenue en prenant en compte la sensibilité à la casse pour discriminer deux identifiants uniques différents.`

**Comment by jxl77** [comment]
Meilleurs Voeux, et merci pour vos efforts. 
J'ai poursuivi un peu mes expérimentations. J'ai toutes les peines du monde à faire l'upload avec Arduino IDE 2.0. 
Le port série se déconnecte tout le temps alors que esptool.py marche très bine seul. 
J'ai donc laissé tomber et repris avec  Plateformeio en mode linge de commande. 
Cela marche beaucoup mieux. 
J'ai pu compiler pour diverses plateformes (Attention, il y a un but qui a été introduit il y a deux jours dans softwareserial).
Pas de problème pour les divers ESP32 Devkit V1. 
En revanche, j'ai bien compilé, et fait l'upload sur un ESP32S3  (lolin_s3) et un ESP32S2  D1 mini, (lolin_s2_mini )
Mais cela ne marche pas. Je prends les configs les plus proches de ce que j'ai. 
Mais il n'y a pas tout.  Mon ESP32S2 mini est de Wemos
Le  ESP32S3, je ne sais pas trop.

**Comment by fanfanlatulipe26** [comment]
J'utilise IDE 1.8.19 sur PC avec le package ESP32 2.0.11 et n'ai pas de problèmes particuliers. J'ai laissé tomber IDE 2 car je trouvais certaines limitations actuelles (?) trop bloquantes. Avez vous essayé le chargement par OTA: cela marche très bien pour moi.
Il y a longtemps que je n'ai pas testé sur ESP8266 avec softwareserial.  J'ai trouvé aussi un très gros problème avec ESP32-C3 et le développeur a du faire de gros changements depuis pour supporter le C3 (le C3 a une horloge qui change dynamiquement a la différence des autres ESP ...). J'ai pour le moment abandonné espsoftwareserial pour les ESP32.

Je n'ai pas testé sur  ESP32S3 et ESP32S2,  mais je pense que la partie point d'accès Wifi devrait fonctionner. A suivre  ...

**Comment by jxl77** [comment]
Sur  le ESP32S3,  j'ai maintenant pu faire compilation et upload,  sur platformio mais 
cela ne marche pas. voici le message d'erreur qui vient de la liaison serie


entry 0x403c98d0
E (27) uart: uart_set_pin(692): tx_io_num error
ESP_ERROR_CHECK failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x4037d474
file: "******/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-uart.c" line 214
func: uartBegin
expression: uart_set_pin(uart_nr, txPin, rxPin, UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE)

abort() was called at PC 0x4037d477 on core 1

**Comment by jxl77** [comment]
j'ai testé la nouvelle version. 4.1b1
J'ai pu  très facilement changer l'Identificateur. C'était important pour moi car je voulais conserver l'identificateur déclaré sur alphatango avant le 31 décembre. Merci pour cette correction. 
J'ai mis le recepteur sur un Lolin32 Lite.  Balise sur Wemos D1 V4.

**Comment by fanfanlatulipe26** [comment]
Erreur sur  ESP32S3 semble indiquer un problème avec la définition des pins pour le GPS  GPS_RX_PIN/GPS_TX_PIN

**Comment by fanfanlatulipe26** [comment]
Résolu avec 4.2

**Comment by jxl77** [comment]
C'est noté. Merci. Je ferai les essais dès que j'aurai un peu de temps libre.
